// ACTIONS FOR CARS
export const GET_ALL_CARS = 'GET_ALL_CARS';
export const CARS_ERROR = 'CARS_ERROR';

// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
